### ISSUE TITLE
Parou de funcionar ! 

### ISSUE THREAD

**Issue by tnascif** [victorharry/zap-gpt#10]
Reprodução do erro: /bot teste 

C:\ProgramData\zap-gpt-main\node_modules\whatsapp-web.js\src\structures\Message.js:91
        this.deviceType = data.id.id.length > 21 ? 'android' : data.id.id.substring(0, 2) == '3A' ? 'ios' : 'web';
                                                                          ^

TypeError: data.id.id.substring is not a function
    at Message._patch (C:\ProgramData\zap-gpt-main\node_modules\whatsapp-web.js\src\structures\Message.js:91:75)
    at new Message (C:\ProgramData\zap-gpt-main\node_modules\whatsapp-web.js\src\structures\Message.js:18:24)
    at Client.sendMessage (C:\ProgramData\zap-gpt-main\node_modules\whatsapp-web.js\src\Client.js:699:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by DisneyMjr** [comment]
aqui tbm tá assim

**Comment by victorharry** [comment]
Vou dar uma olhada pessoal, não tive muito tempo ultimamente pra olhar os projetos pessoais.

**Comment by tnascif** [comment]
Então, acabei dando uma pesquisada aqui, achei esse hot fix que funcionou pra mim. [https://github.com/pedroslopez/whatsapp-web.js/pull/2196/files](url)
